mysite/urls.py
from django.contrib import admin
from django.urls import path
from accounts import views
from calapp import views as cal_views

urlpatterns = [
    path('likelionadmin/', admin.site.urls),
    
    path('',views.login,name='login'),
    
    path('home',views.home,name='home'),
    
    path('signup',views.signup,name='signup'),
    path('signup_detail',views.signup_detail,name='signup_detail'),
    path('logout',views.logout,name='logout'),

    path('delete_all',views.delete_all,name='delete_all'),
    path('delete<int:class_id>',views.delete,name='delete'),
    #path('class_modify<int:class_id>',views.class_modify,name='class_modify'),
    
    #정보 수정 관련 URL
    path('modify/', views.modify, name='modify'),
    path('modify/userinfo', views.modify_userinfo, name='modify_userinfo'),
    path('modify/password', views.modify_password, name='modify_password'),

    #비회원 로그인 URL
    #path('guest_login/', views.guest_login, name = 'guest_login'),
    #path('guest_home/<int:guest_id>', views.guest_home, name = 'guest_home'),
    
    path('calculator',cal_views.calculator, name='calculator'),
    #path('class_delete<int:class_id>',cal_views.class_delete,name='class_delete'),

    path('method', views.method, name='method'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User

class Profile(models.Model): #회원가입 할때 회원 정보들
    user = models.ForeignKey(User,on_delete=models.CASCADE,null=True)
    name = models.CharField(max_length=10,null=True)
    major = models.CharField(max_length=10,null=True)
    ad_year = models.CharField(max_length=10,null=True)

    def __str__(self):
        return self.name or ''


class Guest(models.Model):
    major = models.CharField(max_length=50,null=True)
    ad_year = models.CharField(max_length=50,null=True)

    def __str__(self):
        return self.major

class Lesson(models.Model): #User 객체에 수강한 과목들을 저장함.
    classname = models.CharField(max_length=50,null=True)
    classchoice = (
        ('전공선택','전공선택'),
        ('전공필수','전공필수'),
        ('균형교양','균형교양'),
        ('특화교양','특화교양'),
        ('기초교양','기초교양'),
        ('대학별교양','대학별교양'),
        ('자유선택','자유선택'),
    )
    classkind = models.TextField(max_length=10,null=True,choices=classchoice)
    classcredits = models.IntegerField(null=True)
    link = models.ForeignKey(User,on_delete=models.CASCADE,blank=True, null=True)
    #guest_link = models.ForeignKey(Guest,on_delete=models.CASCADE,blank=True, null=True)
    def __str__(self):
        return self.classkind

calapp/models.py
from django.db import models

class Graduate(models.Model):
    major       = models.CharField(max_length=50,null=True)
    ad_year     = models.CharField(max_length=50,null=True)
    basic       = models.IntegerField(null=True)
    balance     = models.IntegerField(null=True)
    college     = models.IntegerField(null=True)
    free        = models.IntegerField(null=True)    
    needmajor   = models.IntegerField(null=True)
    choicemajor = models.IntegerField(null=True)
    deepmajor   = models.IntegerField(null=True)
    special     = models.IntegerField(null=True)
    teaching    = models.IntegerField(null=True)
    sum         = models.IntegerField(null=True)

    def __str__(self):
        return self.major +" "+ self.ad_year

class ClassList(models.Model):
    kind      = models.CharField(max_length=50,null=True)
    classname = models.CharField(max_length=50,null=True)
    credit    = models.IntegerField(null=True)

    def __str__(self):
        return self.kind + " " + self.classname

calapp/views.py

from django.shortcuts import render,redirect,get_object_or_404
from accounts.models import Profile,Lesson
from calapp.models import Graduate
from django.contrib import messages



def calculator(request):    
    current_user = request.user
    #user_id = user.id
    #userprofile = get_object_or_404(Profile,pk=user_id)
    user_profile = Profile.objects.get(user = current_user)
    gradu_major = user_profile.major
    gradu_ad_year = user_profile.ad_year
    gradu = Graduate.objects.get(major=gradu_major, ad_year=gradu_ad_year)


    choicemajor = Lesson.objects.filter(link = current_user, classkind='전공선택')
    needmajor   = Lesson.objects.filter(link = current_user, classkind='전공필수')
    
    special     = Lesson.objects.filter(link = current_user, classkind='특화교양')
    college     = Lesson.objects.filter(link = current_user, classkind='대학별교양')
    balance     = Lesson.objects.filter(link = current_user, classkind='균형교양')
    basic       = Lesson.objects.filter(link = current_user, classkind='기초교양')
    free        = Lesson.objects.filter(link = current_user, classkind='자유선택')
    teaching    = Lesson.objects.filter(link = current_user, classkind='교직이수')

    choicemajor = add_credit(choicemajor)
    deepmajor = 0
    needmajor = add_credit(needmajor)
    special = add_credit(special)
    college = add_credit(college)
    balance = add_credit(balance)
    basic = add_credit(basic)
    free = add_credit(free)
    teaching = add_credit(teaching)

    
    error_sum = 0

    flag = 0

    if(needmajor < gradu.needmajor):
        flag = 1
        messages.info(request,"전공 필수 학점이 부족합니다.")
    elif(needmajor > gradu.needmajor):
        choicemajor = choicemajor + (needmajor - gradu.needmajor)
        needmajor = gradu.needmajor
        messages.info(request,"전공 필수 학점이 초과되어 전공선택 학점에 추가되었습니다.")

    if(choicemajor < gradu.choicemajor):
        flag = 1
        messages.info(request,"전공 학점이 부족합니다.")
    else:
        deepmajor = choicemajor - gradu.choicemajor
        choicemajor = gradu.choicemajor
        if(deepmajor < gradu.deepmajor):
            flag = 1
            messages.info(request,"심화 전공 학점이 부족합니다.")
        elif(deepmajor > gradu.deepmajor):
            free = free + (deepmajor - gradu.deepmajor)
            deepmajor = gradu.deepmajor
            messages.info(request,"전공 학점이 초과되어 자유선택 학점에 추가되었습니다.")

    if(college < gradu.college):
        flag = 1
        messages.info(request,"대학별 교양 학점이 부족합니다.")
    elif(college > gradu.college):
        free = free + (college - gradu.college)
        error_sum = error_sum + (college - gradu.college)
        college = gradu.college
        messages.info(request,"대학별 교양 학점이 초과되어 자유선택 학점에 추가되었습니다.")

    if(basic < gradu.basic):
        flag = 1
        messages.info(request,"기초 교양 학점이 부족합니다.")
    elif(basic > gradu.basic):
        free = free + (basic - gradu.basic)
        error_sum = error_sum + (basic - gradu.basic)
        basic = gradu.basic
        messages.info(request,"기초 교양 학점이 초과되어 자유선택 학점에 추가되었습니다.")

    if(gradu.special):
        if(special < gradu.special):
            messages.info(request,"특화 교양 학점은 균형교양학점으로 대체됩니다.")
            if((balance+special) < (gradu.balance + gradu.special)):
                flag = 1
                messages.info(request,"균형교양 학점이 부족합니다.")
            elif((balance+special) > (gradu.balance + gradu.special)):
                free = free + (balance + special - gradu.balance - gradu.special)
                error_sum = error_sum + (balance + special - gradu.balance - gradu.special)
                balance = gradu.balance + gradu.special
                messages.info(request,"균형 교양 학점이 초과되어 자유선택 학점에 추가되었습니다.")

        elif(special > gradu.special):
            free = free + (special - gradu.special)
            error_sum = error_sum + (special - gradu.special)
            special = gradu.special
            messages.info(request,"특화 교양 학점이 초과되어 자유선택 학점에 추가되었습니다.")
            if(balance < gradu.balance):
                flag = 1
                messages.info(request,"균형교양 학점이 부족합니다.")
            elif(balance > gradu.balance):
                free = free + (balance - gradu.balance)
                error_sum = error_sum + (balance - gradu.balance)
                balance = gradu.balance
                messages.info(request,"균형 교양 학점이 초과되어 자유선택 학점에 추가되었습니다.")
        else:
            if(balance < gradu.balance):
                flag = 1
                messages.info(request,"균형교양 학점이 부족합니다.")
            elif(balance > gradu.balance):
                free = free + (balance - gradu.balance)
                error_sum = error_sum + (balance - gradu.balance)
                balance = gradu.balance
                messages.info(request,"균형 교양 학점이 초과되어 자유선택 학점에 추가되었습니다.")

    else:
        if(balance < gradu.balance):
            flag = 1
            messages.info(request,"균형교양 학점이 부족합니다.")
        elif(balance > gradu.balance):
            free = free + (balance - gradu.balance)
            error_sum = error_sum + (balance - gradu.balance)
            balance = gradu.balance
            messages.info(request,"균형 교양 학점이 초과되어 자유선택 학점에 추가되었습니다.")

    if(free < gradu.free):
        flag = 1
        messages.info(request,"자유 선택 학점이 부족합니다.")

    if(error_sum > 10):
        messages.info(request,"자유선택으로 인정되는 초과교양 학점은 10학점까지 인정됩니다. 초과 학점은 제외되었습니다.")
        free = free - (error_sum - 10)

    ge_Lessons = {
        '기초교양' : [basic,gradu.basic,gradu.basic-basic],
        '대학별교양' : [college,gradu.college,gradu.college-college],
        '균형교양' : [balance,gradu.balance,gradu.balance-balance],
        '특화교양' : [special,gradu.special,gradu.special-special],
        }


    free_Lessons = {
        '자유선택' : [free,gradu.free,gradu.free-free],
        '교직이수' : [teaching,gradu.teaching,gradu.teaching-teaching],
        }


    major_Lessons = {
        '전공선택' : [choicemajor,gradu.choicemajor,gradu.choicemajor-choicemajor],
        '심화전공' : [deepmajor,gradu.deepmajor,gradu.deepmajor-deepmajor],
        '전공필수' : [needmajor,gradu.needmajor,gradu.needmajor-needmajor],
        }
    
    Lessons = [
    choicemajor,
    deepmajor,
    needmajor,
    special,
    college,
    balance,
    basic,
    free,
    ]

    all_credits = 0
    for credit in Lessons:
        all_credits += credit
        
    remain = gradu.sum - all_credits

    if(flag):
        messages.info(request,"졸업이 불가능 합니다. 학점이 부족합니다.")
    else:
        messages.info(request,"고생하셨습니다. 졸업이 가능합니다.")
    
    
    return render(request,'result.html',{
        'user':current_user,'all':all_credits,'graduate':gradu,
        'ge_class':ge_Lessons,
        'major_class':major_Lessons,
        'free_class':free_Lessons,
        'remain':remain,
        'flag':flag
        })





def add_credit(credits):
    sum = 0
    for credit in credits:
        sum = sum + credit.classcredits
    return sum



def class_delete(request,class_id):
    delete_lesson = get_object_or_404(Lesson, pk=class_id) #수강한 과목 지우기
    delete_lesson.delete()
    return redirect('calculator')

calapp/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<!-- head 태그 이 안에 -->
{% block headcontent %}
{% endblock %}

<body>
    <!-- 중간에 들어갈 내용 -->
    {% block content %}
    {% endblock %}

</body>

</html>

calapp/templates/index.html

{% load static %}

{% block headcontent %}
<!--입력창 너무 지저분함 여기 해결방법 찾기-->

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style type="text/css">
        @import url("{% static 'css/header.css' %}");
        @import url("{% static 'css/footer.css' %}");
    </style>
    <link href="{% static 'css/index.css' %}" rel="stylesheet">
</head>
{% endblock %}

{% block content %}

<!-- header -->
<header class="header">
    <div class="header_wrapper">
        <div class="header_logo">
            <a href="{% url 'home' %}">
                <!--로고 누르면 어디로 가?-->
                <img src="{% static 'img/cal.png'%}" id="headr_img" />
                <h1 class="header_title">학점계산기</h1>
            </a>
        </div>
        <div class="header_inform">
            {% for pro in user.profile_set.all %}
            <label>{{ pro.name }} | </label>
            <label>{{ pro.major }} | </label>
            <label>{{ pro.ad_year }} </label>
            {% endfor %}
        </div>
        <!--여기 어떻게 할지 생각하기-->
        <nav class="header_fix">
            <ul>
                <li><a href="{% url 'logout' %}">로그아웃</a></li>
                <li style="color : #a8aabc">|</li>
                <li><a href="{% url 'modify' %}">정보수정</a></li>
            </ul>
        </nav>
    </div>
</header>

<section class="main">
    <div class="main_wrapper">
        <!-- 과목입력 form -->
        {% if user.is_authenticated %}
        <form method="POST">
            {% csrf_token %}
            <fieldset class="add_border">
                <legend id="add_title">&nbsp;과목 입력&nbsp;</legend>
                <select id="adds_category" name="classkind">
                    <option disabled selected>과목 분류</option>
                    <option value="전공필수">전공필수</option>
                    <option value="전공선택">전공선택</option>
                    <option value="균형교양">균형교양</option>
                    <option value="기초교양">기초교양</option>
                    <option value="대학별교양">대학별교양</option>
                    <option value="특화교양">특화교양</option>
                    <option value="자유선택">자유선택</option>
                </select>
                <input type=text id="adds_class" name="classname" placeholder="과목명">
                <input type=number id="adds_num" name="classcredits" placeholder="학점">
                <button class="adds_button" type="submit">추가</button>
            </fieldset>
        </form>
        {% endif %}

        <div class="end">
            <div class="put">
                <h2 id="put_tit">입력된 과목</h2>
                <a id="put_reset" href="{% url 'delete_all' %}">&nbsp;✔초기화</a>
                <hr id="put_hr">
                <p class="put_plus">-추가버튼을 통해 내용이 입력됩니다</p>
                <button type="submit" class="result_button"
                    onclick="location.href = '{% url 'calculator' %}'">계산하기</button>

                <!--출력 될 내용 형식 (시작-->
                {% if user.lesson_set.all %}
                            
                <div class = "put_inform">             
                    <table class="put_tabel">
                            <tr>
                                <th>과목분류</th><th>과목명</th><th>학점</th><th>&#x2714;</th>
                            </tr>
                            {% for class in user.lesson_set.all %}
                            <tr>
                                <td>{{ class.classkind }}</td> 
                                <td>{{ class.classname }}</td>
                                <td>{{ class.classcredits }}</td>
                                <td><button class="put_butdel" onclick= "location.href = '{% url 'delete' class.id %}'">삭제</button></td>
                            </tr>
                            {% endfor %}
                    </table>
                    <br>
                </div>

                {% endif %}
                <br><br><br><br>
            </div>


            <div class='result'>
                <h2 id="result_tit">이수 학점</h2>
                <hr id="result_hr">
                {% for key,value in credits.items %}
                <!--입력되는 이수 학점 수 형식(시작)-->
                <div class="result_score">
                    <h3 class="score_tit">{{ key }}</h3>
                    <!--아래 내용 다 수정 부탁드려요-->
                    <p class="score_inf"><span id="score_now">{{ value.0 }}&nbsp;</span>/&nbsp;{{ value.1 }}</p>
                </div>
                <!--입력되는 이수 학점 수 형식(완료)-->
                {% endfor %}
            </div>

        </div>

    </div>
</section>

<footer class ="footer">
    <hr id = "footer_hr">
    <div class = "footer_text">
        <ul class="footer_list">
            <li ><a href="javascript:popout()">이용 방법</a></li>
            <li>|</li>
            <li><a href = "javascript:click()">문의 및 건의</li>
        </ul>
        <p class = "copy">© 2022 멋사강원대</p>
    </div>
</footer>

<script>
    
    function click(){ alert('문의 및 건의는 calculator1234@gmail.com으로 연락주세요');}

    function popout() {
        var url = "{% url 'method' %}";
        var name = "method"
        var css = "width = 500, height = 600, top = 10, left = 10"
        window.open(url,name,css )
    }
</script>
{% endblock %}

calapp/templates/login.html
{% load static %}
<!--이미지 출처 남기기-->

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>초기화면 페이지</title>
    <link href="{% static 'css/login.css' %}" rel="stylesheet" />
</head>

<body>
    <!--본문-->
    <section class="main">
        <div class="main_wrapper">
            <h1 class="write_1"> 똑똑한 졸업 도우미,<br>당신의 졸업을 응원합니다</h1>
            <h3 class=write_3>졸업요건<br>계산기</h3>

            <form class="log" method="POST">
                {% csrf_token %}
                <input type='text' placeholder="ID" name="username" /><br>
                <input type='password' placeholder="Password" name="password" /><br>
                <p id="message" style="    display: inline-block;
                padding: 0.7em 0.2em 0 0.1em;
                white-space: nowrap;
                font-size: 0.9rem;
                color : red;
                font-family: 'GmarketSansMedium';
            ">
                    {% if messages %}
                    {% for message in messages %}
                    {{ message.message }}
                    {% endfor %}
                    {% endif %}
                </p><br>
                

                <button type="submit" id="button_log">로그인</button>
                <!--수정함 아이디 빠져 있었음-->
            </form>

            <!--어디에 아이디나 비밀번호 틀렸다고 뜨는거야?-->
            <nav class="nomember_input">
                <ul>
                    <li><a href="{% url 'signup' %}">회원가입 (비회원 이용 불가)</a></li>
                    <!--문구 수정함-->
                </ul>
            </nav>
        </div>
    </section>

    <section class="introduce">
        <div class="introduce_wrapper">
            <h2 class="int_qus">졸업 가능 여부<br>궁금하세요?</h2>
            <hr class="line">
            <h4 class="int_ans"> 입력하고 클릭하면 끝,<br>졸업 가능 여부를<br>빠르게 계산해드려요</h4>
            <h2 class="int_qus2">어떤 수업을 들을지<br>모르겠나요?</h2>
            <hr class="line">
            <h4 class="int_ans2">부족한 과목명과 학점이<br>얼마인지 상세히<br>확인해 알려드려요</h4>
        </div>
    </section>

 <section>
        <div class="photo_wrapper" style="    width : 100%;
        height : 200px;
        margin-bottom: 320px;
        text-align: center;">
            <img src="{% static 'img/phone.png' %}" id="phone" style="width : 245px;
            height: 380px;
            margin-top: 3em;">
            <p id="smart" style="    margin-top : 0.6em;
            margin-bottom: 1em;
            font-family: 'GmarketSansMedium';
            font-weight: bolder;
            font-size: 2rem;
            line-height: 1.2em;
            flex: auto;">언제든, 어디서든<br>편리하게 이용하세요</p>
        </div>
    </section>

    <footer class="footer">
        <hr id="footer_hr">
        <div class="footer_text">
            <ul class="footer_list">
                <li><a href="javascript:popout()">이용 방법</a></li>
                <li>|</li>
                <li><a href="javascript:click()">문의 및 건의</li>
            </ul>
            <p class="copy">© 2022 멋사강원대</p>
        </div>
    </footer>

    <script>

        function click() { alert('문의 및 건의는 calculator1234@gmail.com으로 연락주세요'); }

        function popout() {
            var url = "{% url 'method' %}";
            var name = "method"
            var css = "width = 500, height = 600, top = 10, left = 10"
            window.open(url, name, css)
        }
    </script>
</body>

</html>

calapp/templates/method.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link href="{% static 'css/method.css'%}" rel = "stylesheet">
</head>
<body>
    <div class = wrapper> 
        <h1 id ="tit">이용 방법</h1>
        <h2 class = "sub_tit">1. 로그인하기</h2>
            <h5 class = "int">회원가입을 하지 않은 경우,<br>
            회원가입을 해주시기 바랍니다.</h5>
            <img class="ima" src="{% static 'img/login.png'%}" alt="My Image" width="300" height="346">

            <h2 class = "sub_tit">2. 과목 입력하기</h2>
            <h5 class = "int">1) 현재까지 수강한 과목의<br>
            과목분류, 과목명, 학점을 입력해 주세요.</h5>

            <img class="ima" src="{% static 'img/index1.png'%}" alt="My Image" width="300" height="114">
        

            <h5 class = "int">2) 입력 칸에 정보를 기입한 후<br> 
            추가 버튼을 누르면<br> 
            해당 정보가 과목 창에 나타납니다.</h5>

            <h6 class = "min_tit">* 표의 오른쪽 삭제 버튼을 누르면<br>
            입력한 정보가 삭제됩니다.</h6>

            <img class="ima" src="{% static 'img/index2.png'%}" alt="My Image" width="300" height="414">

            
            <h2 class = "sub_tit">3. 결과보기</h2>
            <h5 class = "int">과목 입력 후 계산하기 버튼을 누르면<br>
            졸업 여부와 상세 설명을 볼 수 있습니다.</h5>
        
            <h6 class = "min_tit">* 해당 결과는 각 대학의 사정에 따라
            <br> 달라질 수 있습니다.</h6>

            <img class="ima" src="{% static 'img/result.png'%}" alt="My Image" width="300" height="272">
    </div>
</body>
</html>

calapp/templates/modify.html
{% extends 'base.html' %}
{% load static %}

{% block headcontent %}

<head>
    <meta charset="utf-8">
    <title>정보수정</title>
    <link rel="stylesheet" href="{% static 'css/modify.css' %}" type="text/css">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <style type="text/css">
        @import url("{% static 'css/footer.css' %}");
    </style>
</head>
{% endblock %}

{% block content %}
<style type="text/css">
    @import url("{% static 'css/header.css' %}");
</style>

<!-- header -->
<header class="header">
    <div class="header_wrapper">
        <div class="header_logo">
            <a href="{% url 'home' %}">
                <!--로고 누르면 어디로 가?-->
                <img src="{% static 'img/cal.png'%}" id="headr_img" />
                <h1 class="header_title">학점계산기</h1>
            </a>
        </div>
        <div class="header_inform">
            {% for pro in user.profile_set.all %}
            <label>{{ pro.name }} | </label>
            <label>{{ pro.major }} | </label>
            <label>{{ pro.ad_year }} </label>
            {% endfor %}
        </div>
        <!--여기 어떻게 할지 생각하기-->
        <nav class="header_fix">
            <ul>
                <li><a href="{% url 'logout' %}">로그아웃</a></li>
                <li style="color : #a8aabc">|</li>
                <li><a href="{% url 'modify' %}">정보수정</a></li>
            </ul>
        </nav>
    </div>
</header>

<div id="wrapper">
    <div id="content">
        <div class="mod_size">
            <label id="mod_tit">정보수정</label>
        </div>

        <form class="modify_inputs" action="{% url 'modify_userinfo' %}" method="POST">
            {% csrf_token %}
            {% for pro in user.profile_set.all %}
            <div class="modify_input">
                <input type="text" name="name" placeholder="{{ pro.name }}" class="modify_in" /><br>
                <input type="text" name="major" placeholder="{{ pro.major }}" class="modify_in" /><br>
                <input type="text" name="admisson_year" placeholder="{{ pro.ad_year }}" class="modify_in" />
            </div>
            {% endfor %}
            <button type="submit" class="button_click">변경하기</button>
        </form>


        <form class="modify_inputs" action="{% url 'modify_password' %}" method="POST">
            {% csrf_token %}
            <div class="modify_input">
                <input type="password" name="curr_password" placeholder="현재 비밀번호" class="modify_in" /><br>
                <input type="password" name="new_password" placeholder="새 비밀번호(문자, 숫자 포함 8~20자)"
                    class="modify_in" /><br>
                <input type="password" name="repeat_password" placeholder="비밀번호 재입력" class="modify_in" /><br>
            </div>
            <div>
                <p id="message" style="    display: inline-block;
                padding: 0.7em 0.2em 0 0.1em;
                white-space: nowrap;
                font-size: 0.9rem;
                color : red;
                font-family: 'GmarketSansMedium';
            ">
                    {% if messages %}
                    {% for message in messages %}
                    {{ message.message }}
                    {% endfor %}
                    {% endif %}
                </p>

            </div>
            <button type="submit" class="button_click">변경하기</button>
        </form>
    </div>
</div>

<footer class="footer">
    <hr id="footer_hr">
    <div class="footer_text">
        <ul class="footer_list">
            <li><a href="javascript:popout()">이용 방법</a></li>
            <li>|</li>
            <li><a href="javascript:click()">문의 및 건의</li>
        </ul>
        <p class="copy">© 2022 멋사강원대</p>
    </div>
</footer>

<script>

    function click() { alert('문의 및 건의는 calculator1234@gmail.com으로 연락주세요'); }

    function popout() {
        var url = "{% url 'method' %}";
        var name = "method"
        var css = "width = 500, height = 600, top = 10, left = 10"
        window.open(url, name, css)
    }
</script>
{% endblock %}

calapp/templates/register.html
{% extends 'base.html' %}
{% load static %}

{% block headcontent %}

<head>
    <meta charset="UTF-8">
    <title>회원가입</title>
    <link rel="stylesheet" href="{% static 'css/register.css' %}" type="text/css">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <style type="text/css">
        @import url("{% static 'css/footer.css' %}");
    </style>
</head>
{% endblock %}

{% block content %}
<div id="wrapper">
    <div id="content">
        <div class="signup_size">
            <label id="signup_tit">회원가입</label>
        </div>
        <form class="signup_form" method="POST">
            {% csrf_token %}
            <div class="box_id">
                <input class="id" type="text" name="username" placeholder="아이디 (6~20자)" size=1px/ id="signup_id">
            </div>

            <div class="signup_passs">
                <input type="password" name="password1" placeholder="비밀번호 (문자,숫자로 8~20자)" class="signup_pass" /> <br>
                <input type="password" name="password2" placeholder="비밀번호 재확인" class="signup_pass" />
                <div id="signup_alr_pss">
                    
                </div>
                <p id="message" style="    display: inline-block;
                padding: 0.7em 0.2em 0 0.1em;
                white-space: nowrap;
                font-size: 0.9rem;
                color : red;
                font-family: 'GmarketSansMedium';
            ">
                    {% if messages %}
                    {% for message in messages %}
                    {{ message.message }}
                    {% endfor %}
                    {% endif %}
                </p>
            </div>
            <button type="submit" id="button_next" style="margin-bottom: 1em;">다음 단계로</button>
        </form>
        
        <div class="text-center" style="margin-bottom: 2px">
            <a id="small" href="{% url 'login' %}" style="    padding: 0.7em 0.2em 0 0.1em;
            font-size: 0.9rem;
            color : #A8AABc;
            font-family: 'GmarketSansMedium';">계정이 있다면? 로그인</a>
        </div>
    </div>
</div>

<footer class="footer">
    <hr id="footer_hr">
    <div class="footer_text">
        <ul class="footer_list">
            <li><a href="javascript:popout()">이용 방법</a></li>
            <li>|</li>
            <li><a href="javascript:click()">문의 및 건의</li>
        </ul>
        <p class="copy">© 2022 멋사강원대</p>
    </div>
</footer>

<script>

    function click() { alert('문의 및 건의는 calculator1234@gmail.com으로 연락주세요'); }

    function popout() {
        var url = "{% url 'method' %}";
        var name = "method"
        var css = "width = 500, height = 600, top = 10, left = 10"
        window.open(url, name, css)
    }
</script>
{% endblock %}